# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My sample book
author: The Jupyter Book Community
logo: _static/logo.png


# Notebook execution settings
execute:
  execute_notebooks: off  # biar gak re-run notebook tiap build

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# References (kalau pakai sitasi)
bibtex_bibfiles:
  - references.bib

# Repository info (buat tombol di pojok kanan atas)
repository:
  url: https://github.com/elpitaa/PSD  # repo kamu
  path_to_book: tugas                  # lokasi folder buku
  branch: main                         # branch yang digunakan

# HTML config (tampilan web)
html:
  favicon: _static/logo.png            # âœ… biar ikon di tab browser juga logo
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false          # opsional
  extra_navbar: ""                     # hapus navbar default (opsional)